Update README.md
Added note to update the LLVM package as a perquisite in Linux because previous versions break the MESA-LOADER for some OpenGL implementations.
Added hints for installing the packages on Arch Linux because of different package names.
Corrected typo in comment in code.
Finally, added the `-lGL` argument to the Linux compile section to avoid "undefined reference to `gl*` errors when compiling.