Update README.md (#95)
Add hints for installing the packages on Arch Linux because of different package names.
Fix typo in comment in code.
Finally, add the `-lGL` argument to the Linux compile section to avoid "undefined reference to `gl*` errors when compiling.